#!/bin/sh
set -eu

SSH_TUNNEL_HOST="${SSH_TUNNEL_HOST:-root@fsd.snowmonkey.co.uk}"
SSH_TUNNEL_LOCAL_PORT="${SSH_TUNNEL_LOCAL_PORT:-5543}"
SSH_TUNNEL_REMOTE_HOST="${SSH_TUNNEL_REMOTE_HOST:-127.0.0.1}"
SSH_TUNNEL_REMOTE_PORT="${SSH_TUNNEL_REMOTE_PORT:-5543}"

exec ssh \
  -o ServerAliveInterval=30 \
  -o ServerAliveCountMax=3 \
  -N \
  -L "${SSH_TUNNEL_LOCAL_PORT}:${SSH_TUNNEL_REMOTE_HOST}:${SSH_TUNNEL_REMOTE_PORT}" \
  "${SSH_TUNNEL_HOST}"
